#!/usr/bin/env python3

"""
8-ball
(run $ mv 8-ball.py /usr/local/bin/8-ball; chmod 755 /usr/local/bin/8-ball to 
put things where they out to be)

A magic 8 ball in Python
"""

import random
import sys
import shutil
import time

STD_RESPONSES = ["It is certain",
                 "It is decidedly so",
                 "Without a doubt",
                 "Yes, definitely",
                 "You may rely on it",
                 "As I see it, yes",
                 "Most likely",
                 "Outlook good",
                 "Yes",
                 "Signs point to yes",
                 "Reply hazy try again",
                 "Ask again later",
                 "Better not tell you now",
                 "Cannot predict now",
                 "Concentrate and ask again",
                 "Don't count on it",
                 "My reply is no",
                 "My sources say no",
                 "Outlook not so good",
                 "Very doubtful"]


if len(sys.argv) == 2:
    question = sys.argv[1]
else:
    question = input("Ask a question of the virtual magic 8-ball:\n")

# ctime()'s resolution is 1s, so you'll get the same response if you ask the
# same question during the same second
random.seed(time.ctime() + " " + question)
response = random.choice(STD_RESPONSES)

if sys.stdout.isatty():
    response = '\n{}\n'.format(response.center\
                               (shutil.get_terminal_size((80,20))[0],' '))

print("{}".format(response))
