#!/usr/bin/env python3

"""
8ball.py

A magic 8 ball in Python
"""

import random
import sys
import shutil

random.seed()

STD_RESPONSES = ["It is certain",
                 "It is decidedly so",
                 "Without a doubt",
                 "Yes, definitely",
                 "You may rely on it",
                 "As I see it, yes",
                 "Most likely",
                 "Outlook good",
                 "Yes",
                 "Signs point to yes",
                 "Reply hazy try again",
                 "Ask again later",
                 "Better not tell you now",
                 "Cannot predict now",
                 "Concentrate and ask again",
                 "Don't count on it",
                 "My reply is no",
                 "My sources say no",
                 "Outlook not so good",
                 "Very doubtful"]


if len(sys.argv) == 2:
    question = sys.argv[1]
else:
    question = raw_input("Ask a question of the virtual magic 8-ball:\n")

response = random.choice(STD_RESPONSES)
del question

if sys.stdout.isatty():
    response = '\n{}\n'.format(response.center\
                               (shutil.get_terminal_size((80,20))[0],' '))

print("{}".format(response))
