#!/usr/bin/env python3
"""
pwchars

takes an argument of special characters and returns those characters at the
end of [A-Za-z0-0] and ensures that there are no duplicate characters

since this just prints the string to stdout, it's probably a good idea to pipe
it into pbcopy, e.g.
   
  $ pwchars '%*#@ you' | pbcopy
"""

import sys


def main():
    uppers = [chr(i) for i in range(ord('A'),ord('Z')+1)]
    lowers = [chr(i) for i in range(ord('a'),ord('z')+1)]
    numbers = [chr(i) for i in range(ord('0'),ord('9')+1)]

    try:
        special_chars = list(sys.argv[1])
    except IndexError:
        special_chars = []

    print("".join(sorted(list(set(uppers+lowers+numbers+special_chars)))))

    return 0


if __name__ == "__main__":
    sys.exit(main())
