#!/usr/bin/env python3
"""
randomchoices.py

Doing this to speed up my random choosing of things
"""

import random
import sys

if len(sys.argv) > 1:
    choices = sys.argv[1:]
else:
    choices = []

choice_count = len(choices)

if not choices:
    print("\nInput your choices on separate lines below, and Python, in its\n"
          "infinite wisdom, will randomly select one of them for you.  Terminate\n"
          "your choices with a blank line.\n")

    prev_choice = True

    while prev_choice:
        choice_count += 1
        new_choice = input("choice {}: ".format(choice_count))
        if new_choice:
            choices.append(new_choice)
        prev_choice = new_choice

    random.seed()    
if choice_count < 2:
    print("\nYou've given me nothing from which to choose. Goodbye!")
else:
    print("\nPython has chosen '\033[1;30m{}\033[0m' for you.\n"
          "".format(random.choice(choices)))
